// Niall's Test Case 6: more than one error

#include <iostream>
#include <fstream>
#include <string>
#include <math.h>
#include <cstdlib>
#include <unistd.h>

using namespace std;


int main(void)  {
   int x[10];

   cout << "Hello world, this is Test Case 6, which has several errors." << endl;
   cout << "x[8]=" << (x[8)] << end;
   cout << "Hello again: "<< endl;
   cout << "(1+2)=" << 1+2) << end;
   return 0;
    
}
